### PR TITLE
CacheMode performance, Better ripple fx, Custom ripple ink, Fix for textbox scrollbars

### PR DESCRIPTION
**Pull request by xaviergonz**
This is a megamix of all my previous pull requests

CACHE MODE PERFORMANCE:
Basically added decorators with the cache mode enabled wrapping elements with associated shadow effects wherever possible in order to speed up performance by a lot. Its effects can be seen on the flyout animations of the demo app for example.

BETTER RAISED BUTTONS:
While at it fixed the buttons so they are rounded as per google spec. The shadow border was square and on top of the rounded background border, thus hiding it.
Also removed some animations and elements that never were used.
Oh and also now they support a border brush and thickness.

BETTER RIPPLE FX:
As said, tweaked the animations so they look more like polymer

CUSTOM RIPPLE INK:
Added ink color selectable via RippleAssist.Feedback where possible.
Fixed action popup box so the ripples are non centered

Other small fixes, like fix so when a scrollbar is set to visible it shows on its proper position.

### CODE REVIEW

**Comment by punker76** [comment]
@xaviergonz why this many changes in one pr?

**Comment by ButchersBoy** [comment]
Dude, your PR's were better before...I'd rather look at the CacheMode stuff in isolation when I can fire it up on some different setups/displays...

**Comment by punker76** [comment]
@ButchersBoy :+1:

**Comment by xaviergonz** [comment]
Because it was getting messy and my git decided to merge the custom ripple
ink pull request with all the others :(

**Comment by ButchersBoy** [comment]
@xaviergonz please break back into 3:

* CACHE MODE PERFORMANCE
* BETTER RAISED BUTTONS
* BETTER RIPPLE FX / CUSTOM RIPPLE INK

You changes are appreciated but I need to review PR on its own merit and my time is limited.

**Comment by ButchersBoy** [comment]
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/CONTRIBUTING.md#submitting-a-pr

**Comment by xaviergonz** [comment]
done, however better raised buttons depends on cache mode performance and custom ripple ink on better raised buttons, so ill put pull requests for those if the first is accepted.

**Pull request closed without merging**
