### PR TITLE
Fix Menu

### PR DESCRIPTION
**Pull request by l1pton17**
Sorry, i forgot to change some properties in accordance with md spec (right-padding was 16dp, but must be 24)

### CODE REVIEW

**Comment by ButchersBoy** [comment]
The latest bold text on the menu is making the menu jump around by a pixel when moving the mouse left/rght...

**Comment by l1pton17** [comment]
@ButchersBoy yeah, i have noticed it. Maybe i can resolve this problem in the evening.

**Comment by ButchersBoy** [comment]
Do we even need the bold?

https://www.google.com/design/spec/components/menus.html#menus-usage

**Comment by l1pton17** [comment]
@ButchersBoy wow, on pictures they don't use bold text but on video they do :) So, i suppose there is no so much reason to implement this.

**Comment by ButchersBoy** [comment]
:confused: ...not the first time I have found contradictions...

**Comment by l1pton17** [comment]
Forgot to left a message.
Fixed, i let bold working. Now width of menuitem doesn't change.

**Comment by ButchersBoy** [comment]
So we are sticking with bold?

**Comment by QuantumDeveloper** [comment]
@l1pton17 you are very active)
Maybe you can also do some fixes to the Dragablz ;)

**Comment by l1pton17** [comment]
Why not.
Do you want me to remove bold? I fixed shifting arround a pixel when moving mouse.
According to specs it can be bold.

**Comment by ButchersBoy** [comment]
I only ask cos there is no bold on here: https://www.google.com/design/spec/components/menus.html#
Before you remove it, what is the video you are talking about?

**Comment by ButchersBoy** [comment]
(It does look good though - merged)...but please link the videos so I can see what you are looking at.

**Comment by l1pton17** [comment]
@ButchersBoy here: https://goo.gl/KpXrzq

**Comment by ButchersBoy** [comment]
thanks

**Pull request merged**
