### PR TITLE
Properties for controlling the transition origin

### PR DESCRIPTION
**Pull request by mgnslndh**

### CODE REVIEW

**Comment by mgnslndh** [comment]
It is not necessary at all. Just for convenience.

**Comment by ButchersBoy** [comment]
Yes please.  We can always add it in later if it proves to be of common use; I just don't want to add stuff that becomes a permanent part of the public API unnecessarily.   ...maybe it will prove it's worth in the future and we can add it back.

**Comment by mgnslndh** [comment]
You're right, i'll fix it tonight

**Comment by ButchersBoy** [comment]
I've got 5 mins, I'll merge myself and move the Points.

**Pull request merged**
