### PR TITLE
Floating hints animate to HintOpacity instead of 100%

### PR DESCRIPTION
**Pull request by EdonGashi**
Non empty visual state of SmartHint will animate to the value of HintOpacity property instead of 100%, which will cause floating hints to maintain color while moving upwards.

As noted in #379 and clearly seen in the [spec](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3eC03VnhOekZxWW8/components_textfields_counter3.png) hints have less opacity than the control content.

Because focused controls override the floating hint color to the PrimaryHueMidBrush, an override of HintOpacity to 100% is added on their data triggers.

Additionally, TimePicker was missing such a trigger, which I have added in this PR.

Screenshot comparison below:

compared

### CODE REVIEW

**Comment by ButchersBoy** [comment]
Hi @EdonGashi, thanks for this,  looks good; one small bug:

non-editable combos dont pick up the accent colour when they have focus (all  other controls work fine):

image

**Comment by EdonGashi** [comment]
I am looking into it. I will update once I find a solution. Thanks

**Comment by EdonGashi** [comment]
I downloaded the latest master and this bug occurs even without my updates. Set the primary color to yellow or something distinct as purple is hard to notice. It seems that changing the combo's selection once or twice fixes it afterwards...

**Comment by ButchersBoy** [comment]
OK, I'll pull in the PR...if you find a fix in the future another PR would be welcome.

**Comment by ButchersBoy** [comment]
Thank-you, and welcome to the contributors list!

**Comment by redcurry** [comment]
Looking at another theme, however, (see https://material.google.com/components/text-fields.html#text-fields-labels), the hint and underline colors may be set to something else, like an accent color.

**Pull request merged**
