### PR TITLE
WIP - Progress Buttons

### PR DESCRIPTION
**Pull request by ButchersBoy**
To achieve

* Progress raised button (as in Google Navigation app, "DISMISS" button)
* Floating action progress button (see "Circular with integration" https://material.io/guidelines/components/progress-activity.html#progress-activity-types-of-indicators )

### CODE REVIEW

**Comment by ButchersBoy** [comment]
Raised Button:

raisedbuttonwithprogress

**Comment by mgnslndh** [comment]
Holy sweetness, Looking good!

**Comment by chetank628** [comment]
Can any body give me the dummy code or steps to follow to implement floating action button

**Comment by jespersh** [comment]
@chetank628 - I found these parts when I was looking into the same yesterday:
* the button xaml code: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Buttons.xaml#L283
* the running command code: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/ButtonsViewModel.cs#L69 along with the region on line 137

**Pull request merged**
