### PR TITLE
Recommended colors

### PR DESCRIPTION
**Pull request by Davipb**
It's easy to see most people will want to use the predefined color swatches in their programs. As such, having to manually define the brushes seems unnecessary work:

```xml
<ResourceDictionary.MergedDictionaries>
    <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/MaterialDesignColor.Blue.Named.xaml" />
    <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/MaterialDesignColor.Lime.Named.xaml" />
</ResourceDictionary.MergedDictionaries>

<SolidColorBrush x:Key="PrimaryHueLightBrush" Color="{StaticResource BluePrimary200}"/>
<SolidColorBrush x:Key="PrimaryHueLightForegroundBrush" Color="{StaticResource BluePrimary200Foreground}"/>
<SolidColorBrush x:Key="PrimaryHueMidBrush" Color="{StaticResource BluePrimary500}"/>
<SolidColorBrush x:Key="PrimaryHueMidForegroundBrush" Color="{StaticResource BluePrimary500Foreground}"/>
<SolidColorBrush x:Key="PrimaryHueDarkBrush" Color="{StaticResource BluePrimary700}"/>
<SolidColorBrush x:Key="PrimaryHueDarkForegroundBrush" Color="{StaticResource BluePrimary700Foreground}"/>

<SolidColorBrush x:Key="SecondaryAccentBrush" Color="{StaticResource LimeAccent700}"/>
<SolidColorBrush x:Key="SecondaryAccentForegroundBrush" Color="{StaticResource LimeAccent700Foreground}"/>
```

With the new "Recommended Colors", users can reduce all those lines to just these two:

```xml
<ResourceDictionary.MergedDictionaries>
    <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/Blue.xaml" />
    <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/Lime.xaml" />
</ResourceDictionary.MergedDictionaries>
```

### CODE REVIEW

**Comment by ButchersBoy** [comment]
Hey looks good...am just pondering on the naming conventions like I mentioned in your other PR...but in this case the shorter name works well with your folder structure...

Thoughts?

You've tested the palette switcher still works, right?

**Comment by l1pton17** [comment]
Does anyone have idea about how to make an access to current PrimaryHueMidColor not brush? I mean, when you want to make a ColorAnimation to current PrimaryHueMidBrush color, you can't do this, 'cause Primary500 color has been overridden by accent color's resourcedictionary.
What you think about to split each colors dictionary into 2 dictionaries: primary and accent, and include only what you need? So when you include them, they are not overlapped each other. And you can use Primary* colors.

**Comment by ButchersBoy** [comment]
@Davipb I can see some bad names: "StaticResource Deep OrangePrimary200Foreground"

**Comment by ButchersBoy** [comment]
@l1pton17 I'm OK with this.  It's another breaking change, but for the best.  It's also explicit as some swatches don't even support accents.

@Davipb ...do you fancy doing this as part of this PR?

**Comment by ButchersBoy** [comment]
In fact, so long as we don't delete any of the existing swatches, it wont be a breaking change.

If we were to be really pedantic, we would haven

MaterialDesignColor._Colour_.xaml
MaterialDesignColor._Colour_.Named.xaml
MaterialDesignColor._Colour_.Primary.xaml
MaterialDesignColor._Colour_.Accent.xaml
MaterialDesignColor._Colour_.Named.Primary.xaml
MaterialDesignColor._Colour_.Named.Accent.xaml

Then we wouldn't break people's existing App.xamls, and people could migrate over time.

The mdresgen project can be hacked to do this.... (that's how all the swatches were generated in the first place).

**Comment by Davipb** [comment]
@ButchersBoy Deep Orange seems fine to me, it's exactly as define in the color swatches: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/Themes/MaterialDesignColor.DeepOrange.Named.xaml

I will be making all the changes you recommended ASAP. If you're interested, this is the program I used to create these files: https://gist.github.com/Davipb/d2fe87d4d7034ce69d70

**Comment by ButchersBoy** [comment]
Cool.  No rush.  If you can, use mdresgen tool, that's the "official" generator, and means we can all regenerate them.

**Comment by Davipb** [comment]
Alright, so now the MaterialDesignColors project has the following files:

**Legacy Swatches:** (Just to maintain backwards compability)
Themes\MaterialDesignColor.*Color*.xaml
Themes\MaterialDesignColor.*Color*.Named.xaml

**New Swatches:**
Themes\MaterialDesignColor.*Color*.Primary.xaml
Themes\MaterialDesignColor.*Color*.Accent.xaml
Themes\MaterialDesignColor.*Color*.Named.Primary.xaml
Themes\MaterialDesignColor.*Color*.Named.Accent.xaml

**Recommended Colors:** (The same as in the original pull request, only renamed & relocated)
Themes\Recommended\Primary\MaterialDesignColor.*Color*.xaml
Themes\Recommended\Accent\MaterialDesignColor.*Color*.xaml

I've also changed mdresgen to generate these new files, in case they need to be recovered.

Currently, the only problem we're having is using the Pallete Switcher with MahApps. Material Design controls change just fine, but MahApps controls don't. I assume this is because the SwatchesProvider/PaletterHelper is still using the legacy xaml files, but I'm still analyzing these classes (any help is appreciated).

**Comment by Davipb** [comment]
Alright, I found the problem: PaletteHelper only changes MahApps brushes if they are declared in the same Dictionary as the Material Brushes. In fact, it only correctly affects material brushes themselves if they are declared in the exact same dictionary, and doesn't actually replace the Primary* / Accent* color definitions, which makes it incompatible with **8l1pton17's** idea altogether. 

The only idea I have for fixing this is making it look through every single merged 'child' dictionary (and their merged dictionaries, and so on) and replace the individual Primary* / Accent* entries, instead of whole dictionaries. If we then use DynamicResources whenever we call those colors, the Pallete Helper will be compatible with almost anything, albeit a bit slower.

**Comment by Davipb** [comment]
Alright, it's done. Now PalletteHelper and SwatchesProvider work just fine and use the new swatches!

**Comment by ButchersBoy** [comment]
Excellent...I like this...the app.xaml is super-simple now, but we are backwards compatible, and people can still tweak the hues if they want.  I went to look at your other PR (on the MahApps Flyouts) but it's now got a merge conflict...

**Comment by punker76** [comment]
:+1:

**Comment by Davipb** [comment]
Yeah, they both alter the app.xaml, am fixing it right now

**Pull request merged**
