### PR TITLE
Custom ink where possible

### PR DESCRIPTION
**Pull request by xaviergonz**
Using new RippleAssist.Feedback attached prop

### CODE REVIEW

**Comment by xaviergonz** [comment]
It is based on an older version so some changes might be needed.

**Comment by ButchersBoy** [comment]
@xaviergonz dunno if you noticed but this is currently conflicting.

**Comment by xaviergonz** [comment]
Yeah, I just haven't had the time recently to fix the commit since it was based on an old version.

**Comment by SuicSoft** [comment]
@xaviergonz You can solve your merge conflicts using GitHub for Windows

**Comment by SuicSoft** [comment]
Overwrite your changes with the new version and update the new version to your needs

**Comment by ButchersBoy** [comment]
Hi @xaviergonz thanks for your input on this, another PR has gone in to cover custom ripple covers.  Your work was inspiration so appreciated.

James

**Comment by xaviergonz** [comment]
I'm glad it could serve as inspiration :) :+1:

**Pull request closed without merging**
