### PR TITLE
Combobox background

### LINKED ISSUE #352: Combo box UI element selected item transparency
Combo box drop down on selected item has transparency, if background color doesn't match combo box it becomes apparent. 

image

### PR DESCRIPTION
**Pull request by l1pton17**
ComobBox uses Background property, fix #352 (Up and simple templates are considered too).

ex1
ex2

And also fix DownVerticalOffset to get rid of this:
image

### CODE REVIEW

**Comment by ButchersBoy** [comment]
Cool, looking better, :+1: .  I've removed the public margin from password box to bring it in line.  Also I've tweaked the padding on the combo trying to bring all the underlines level in the demo.  We are still 1 pixel out in a couple of places.

**Comment by ButchersBoy** [comment]
hmmm...

image

**Comment by l1pton17** [comment]
@ButchersBoy yeah, doesn't look good. and why comobobox so wide?

**Comment by ButchersBoy** [comment]
Yeah, I need to shrink the combo box, but it's still a possibility.  I think eventually we need to add an Assist so that you can turn off the default cut out mode where you might be a bit short on space.

**Comment by l1pton17** [comment]
@ButchersBoy wait a few days, please. i have an idea how to solve this problem :smile:

**Comment by l1pton17** [comment]
@ButchersBoy how did you get this?
i can't:
image

**Comment by l1pton17** [comment]
@ButchersBoy sorry for delay, i caught a cold :smile:

**Comment by ButchersBoy** [comment]
Don't worry.  Don't want to rush.  Want the good shit.  :)

Whenever you are ready.

**Pull request merged**
