### PR TITLE
Implement ExpansionPanel control

### PR DESCRIPTION
**Pull request by JeffBarnard**
Hi there! First off, great work, your project has been a huge help and inspiration for me. I hope that I can offer something in return.  I've implemented a material design Expansion Panel control as described in the spec here [https://material.io/guidelines/components/expansion-panels.html](https://material.io/guidelines/components/expansion-panels.html)
I've amended the Expansion view to showcase the new control, please check it out and consider it for your project.  

image

Perhaps you can think of some improvements or alternate method to implement this behavior, any questions/concerns please let me know.  It acts like an ListBox/ItemsControl, but contains an internal Expander. You can use it by binding to a collection and defining your header and content DataTemplates, a trigger can easily be used to change header when the item is selected. I thought about defining a third DataTemplate for the expanded Header but couldn't manage to do that.

`<materialDesign:ExpansionPanel ItemsSource="{StaticResource BindingCollection}" ItemHeaderTemplate="{StaticResource ExpansionPanelHeaderTemplate}" ItemTemplate="{StaticResource ExpansionPanelContentTemplate}">`

Jeff Barnard

### CODE REVIEW

**Comment by maciz84** [comment]
This is awesome great job Jeff

**Comment by ButchersBoy** [comment]
Hey, looks pretty nice, I will have a closer look soon.

**Comment by BryceBarbara** [comment]
Wow this looks great! It looks like it might need the flat toolbar button styles on the save/cancel? It also appears to be missing a border between the buttons and the rest of the content. Was that intentional?

image

**Comment by JeffBarnard** [comment]
The content I chose to display is just an example, you can template whatever content you wish. I intentionally left it generic, the control does not force any particular content/buttons on the consumer, it's simply an accordion container.

**Comment by JeffBarnard** [comment]
Closing, my source code is out of date.

**Pull request closed without merging**
