### PR TITLE
Improved control over DialogHost popup

### PR DESCRIPTION
**Pull request by Keboo**
Address issue #655 though not in the way requested.

Added a style to control the Popup in the dialog host and created a default style that would allow consumers to either extend or override the default values as they see fit.
I personally like this option better than simply adding an attached property because it gives greater control and is more discoverable.

### CODE REVIEW

**Comment by Keboo** [comment]
@ButchersBoy my changes were initially failing the build because I used C# 7 expression syntax for the property. It looks like AppVeyor just recently updated their build environment images to include VS2017. Any chance on getting that bumped up?

**Comment by elvince** [comment]
Hi guys,

Can you explain me is something is blocking this request and why it hasn't been pushed witht he 2.3.1?

for your recall, it is linked to : #665, #657, #658.


Thanks,

**Comment by Keboo** [comment]
Hi @elvince right now @ButchersBoy  is out taking care of some personal issues. Once he gets time I am sure he will review the PRs (as there are quite a few outstanding). If you need this change sooner, you can always fork the repository and merge this into it and compile the library locally.

**Comment by ButchersBoy** [comment]
Hi, just caught me at 7am before I move home today!  Merged, thanks @Keboo 

@elvince it will be in the latest ci build on nuget shortly.

**Comment by elvince** [comment]
Thanks Guys. 
@ButchersBoy If you will be out for a long (I can understand), you might select the best contributors and might be grant them the ability to merge and deploy nuget package so the project will still be active? 
you develop a nice package/tool, it should be a shame that it drop from active to inactive :(

GL for your personal stuff.

**Pull request merged**
