### PR TITLE
Bugfix: the PopupBox resource dictionary wasn't exported.

### PR DESCRIPTION
**Pull request by adrianhara**

### CODE REVIEW

**Comment by adrianhara** [comment]
Any input on this? Or could be merged?

**Comment by ButchersBoy** [comment]
Well, I'm holiday... But there is a reason why it is like that:

All themes of standard WPF controls are exported. PopupBox is a custom control for this library. For library custom controls, default templates are set up in generic.xaml.

The PopupBox is special still, as it has a default style, but also the extra style for the FAB variant, so these are current pull-in on demand.

So, it's by design. But I'm thinking about it some more.

**Comment by adrianhara** [comment]
I see. I'm wondering, what would be the disadvantage of exporting it? DLL size?

**Comment by adrianhara** [comment]
Closed it as: nevermind 😸

**Pull request closed without merging**
