### PR TITLE
Fix a bug in Demo and added new control : PopupBoxItem

### PR DESCRIPTION
**Pull request by wongjiahau**
-Clicking the 'Copy to clipboard' button will cause the application to crash.
-Now the bug is fixed
-Also, now snackbar will be shown to notify user that the code is copied to clipboard

### CODE REVIEW

**Comment by wongjiahau** [comment]
untitled

**Comment by ButchersBoy** [comment]
Hi,

If we are going to add ```PopupBoxItem``` then it's style needs to be set in XAML, not in it's constructor.

Can we have these two things as two individual pull requests, so I can review each change in isolation please.

**Comment by wongjiahau** [comment]
Ok sure, I'll set the style into XAML, and will make these 2 commits and individual pull requests. 
Thank you for the reply. 
I'm very glad that you replied because this is my first attempt to try to contribute to an open source project :)

**Comment by Keboo** [comment]
Looks like this PR can be close now that #749 and #750 contain the relevant pieces.

**Pull request closed without merging**
