### PR TITLE
Changed clock hand dragging behavior

### PR DESCRIPTION
**Pull request by Tokter**
Changes the dragging behavior of the clock hands to this:

clock

That's my first PR ever, please let me know if I did something wrong.

### CODE REVIEW

**Comment by ButchersBoy** [comment]
Perfect.  :+1:

**Comment by quicoli** [comment]
Fantastic! Great job!

I didn't get time to check it out "in person" yet, but, is there some
property to change time behavior to 24H mode? (instead of AM/PM, handle
something like 13:00 (1:00 pm)) What google guidance suggest for those
cases?




2015-04-27 12:07 GMT-03:00 Markus Luedin <notifications@github.com>:

**Comment by quicoli** [comment]
I believe here we have an idea how an analog 24H clock might look...

http://www.botta-design.de/en/einzeigeruhr-uno-24.html

bye

2015-04-27 12:07 GMT-03:00 Markus Luedin <notifications@github.com>:

**Comment by ButchersBoy** [comment]
lol...i was just waiting for that request  :)   I will try get to it at some point.  interestingly, I was looking at the 24hr mode on keep on my phone, but in their online guidelines they dont mention it...   but yeah, that's a bit of a "stretch" goal right now.  At least this works.  (The TImePicker part will display in 24 hours).

**Pull request merged**
