### PR TITLE
Allow 12:00am as initial time selection

### LINKED ISSUE #689: TimePicker selecting 12:00AM to start
The time picker will not accept a time of 12:00 am on the first try. It will accept it any following try though and accepts any time but 12:00AM the first time through.

```
<materialDesign:TimePicker>
      <materialDesign:TimePicker.SelectedTime>
            <Binding Path="LabCase.RequestedBackTime" UpdateSourceTrigger="PropertyChanged">
                 <Binding.ValidationRules>
                     <validationRules:NullValidationRule/>
                </Binding.ValidationRules>
            </Binding>
     </materialDesign:TimePicker.SelectedTime>
</materialDesign:TimePicker>
```

So it seems like it is a null object if it is 12:00 am on the first set.

### PR DESCRIPTION
**Pull request by Keboo**
Fixes #689 

Fixing issue where 12:00am would not be selected as the initial time.
Also clean up whitespace. If this is not desirable let me know and I can re-submit without it.

### CODE REVIEW

**Comment by BryceBarbara** [comment]
It looks like your commit contains a ton of unrelated changes due to formatting changes? That may be a thing preventing acceptance.

**Comment by Keboo** [comment]
@BryceBarbara fixed. Though I tend to just append ?w=1 on github compares to filter out white space changes.

**Comment by ButchersBoy** [comment]
This seems to have a negative effect.  When using TimePicker, previously the user selected the hour, then the clock automatically moved into minutes mode, and once the minutes were selected, the popup would close.

With this change, the popup closes immediately upon hour selection.

**Comment by Keboo** [comment]
@ButchersBoy my apologies. It should be working correctly now.

**Comment by ButchersBoy** [comment]
Cool, thank you!

**Pull request merged**
