### PR TITLE
added Style for ListView and ListViewItem

### PR DESCRIPTION
**Pull request by Insire**
added default styles for ListView and ListViewItem

### CODE REVIEW

**Comment by Insire** [comment]
Let me know if this is acceptible. (first pull request )

**Comment by ButchersBoy** [comment]
Hi,

This looks good and will help plug a big gap.

One issue, when re-organising columns, the indicator doesn't seem to follow palette:

image

**Comment by Insire** [comment]
I'll have a look.

**Comment by ButchersBoy** [comment]
OK fair enough...I'll take a look at some point in the future.

**Comment by Insire** [comment]
I just spend a few hours googling on how to style that drag/ drop thingie. Still not wiser.

What i managed to find was the Role Property for the GridViewColumnHeader. So I added a colored border to the Header when dragging it, similar to what the datagrid already has. I also moved the ThumbStyles for the ListView, DataGrid and the default style to its own ResourceDictionary.

**Comment by ButchersBoy** [comment]
Thankyou.

Had to add few extra to ensure the standard ListView (without GridView) style worked.  I'll try and come back and look at the dragging cursor later.

**Pull request merged**
