### PR TITLE
MahApps integration

### PR DESCRIPTION
**Pull request by Davipb**
I realized that the MahApps project was empty, so I decided to help.

I moved the Dialog XAML to its proper project and added a Fonts.xaml to change MahApp's default font (which is Segoe UI) to Roboto, but the biggest change is a custom style to the Flyouts, which I believe fits Material Design much better:

material-mahapps-dragablz_mash_up_2015-09-26_14-22-48

material-mahapps-dragablz_mash_up_2015-09-26_14-23-25

### CODE REVIEW

**Comment by quicoli** [comment]
Wow! Great!

Enviado pelo meu Windows Phone 

-----Mensagem Original-----
De: "Davipb" <notifications@github.com>
Enviada em: ‎26/‎09/‎2015 14:30
Para: "ButchersBoy/MaterialDesignInXamlToolkit" <MaterialDesignInXamlToolkit@noreply.github.com>
Assunto: [MaterialDesignInXamlToolkit] MahApps integration (#70)

I realized that the MahApps project was empty, so I decided to help.
I moved the Dialog XAML to its proper project and added a Fonts.xaml to change MahApp's default font (which is Segoe UI) to Roboto, but the biggest change is a custom style to the Flyouts, which I believe fits Material Design much better:





You can view, comment on, or merge this pull request online at:
  https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/pull/70
Commit Summary
Add Dialogs.xaml and Fonts.xaml 
Remove MahApps xamls from main project 
Add Flyout material style 
File Changes
M MahMaterialDragablzMashUp/App.xaml (92) 
M MahMaterialDragablzMashUp/DialogsViewModel.cs (20) 
M MahMaterialDragablzMashUp/MahMaterialDragablzMashUp.csproj (4) 
M MaterialDesignThemes.MahApps/MaterialDesignThemes.MahApps.csproj (29) 
M MaterialDesignThemes.MahApps/Properties/Resources.Designer.cs (3) 
M MaterialDesignThemes.MahApps/Properties/Settings.Designer.cs (14) 
D MaterialDesignThemes.MahApps/Themes/Dialog.xaml (4) 
R MaterialDesignThemes.MahApps/Themes/Dialogs.xaml (4) 
A MaterialDesignThemes.MahApps/Themes/Flyout.xaml (280) 
A MaterialDesignThemes.MahApps/Themes/Fonts.xaml (10) 
A MaterialDesignThemes.MahApps/packages.config (4) 
M MaterialDesignThemes.Wpf/MaterialDesignThemes.Wpf.csproj (4) 
Patch Links:
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/pull/70.patch 
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/pull/70.diff

**Comment by ButchersBoy** [comment]
Hi,

* This is a breaking change.  Can we leave MaterialDesignTheme.MahApps.Dialogs.xaml in it's existing place please, and have a **copy** in the .MahApps assembly.  I have stuff I will be putting into the .MahApps assemebly, but there's no nuget package (and I don't want to create one _just_ yet), so let's do a phased deprecation.  
* Can we stick to the naming convention MaterialDesignTheme.MahApps.*.xaml.  It's a bit long winded but it's in keeping with with the rest of the project.
* I don't actually like the action button.  To quote Google "Floating action buttons are used for a promoted action."  All this does is close the flyout.  Also, they recommend trying to stick to one per "page".  We would be kind of seizing that from other users creations.  Also the arrow is very Metro.  Can you make it a bit more discrete?  Maybe try with the Tool button style we have, with this icon: https://materialdesignicons.com/icon/arrow-left

Thanks.

**Comment by Davipb** [comment]
Done. Original file is back in its place, new files are following the naming convention, and the flyout button is more material:

material-mahapps-dragablz_mash_up_2015-09-29_13-50-08

material-mahapps-dragablz_mash_up_2015-09-29_13-50-20

**Comment by ButchersBoy** [comment]
Looks smart!

**Comment by Davipb** [comment]
Alright, the PR is now updated to resolve any merge conflicts

**Comment by ButchersBoy** [comment]
thanks

**Pull request merged**
