### PR TITLE
Fix ComboBox dpi issue

### PR DESCRIPTION
**Pull request by l1pton17**
Fix issue #145

### CODE REVIEW

**Comment by ButchersBoy** [comment]
Just had a quick look on my laptop, this is opening up above.  Haven't  got time to investigate just yet.

image

**Comment by ButchersBoy** [comment]
(Clipping issue looks better though)

**Comment by l1pton17** [comment]
@ButchersBoy i fixed some bugs, but i don't know will it fix your laptop issue (i don't have a laptop).
Also it works bad on two monitos with different dpi, but i can't imagine a man who have two monitors with different dpi.

**Comment by ButchersBoy** [comment]
Well done, works on the laptop!

**Pull request merged**
